import React, { useState, useEffect } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import {
  Scale, Building2, MessageSquare, FileText, FolderOpen,
  ChevronRight, ArrowLeft, Zap, Lock, Plus
} from 'lucide-react';
import axios from 'axios';
import { toast } from 'sonner';
import { useAuth } from '../context/AuthContext';
import ProfileManager from './legal/ProfileManager';
import ChatIntake from './legal/ChatIntake';
import DocumentCatalog from './legal/DocumentCatalog';
import DocumentVault from './legal/DocumentVault';
import TopupModal from './legal/TopupModal';

const API = process.env.REACT_APP_BACKEND_URL || '';

// ─── Views ────────────────────────────────────────────────────────────────────
// profiles → (select profile) → profile_home → chat | catalog | vault

const DISCLAIMER_TEXT =
  'Documents generated by LaunchBusiness AI are AI-drafted starting points only. ' +
  'They have not been reviewed by a licensed attorney. NovaJay Tech makes no guarantee ' +
  'of legal validity or compliance. Always have documents reviewed by a qualified lawyer ' +
  'before signing, publishing, or relying on them.';

export default function LegalDocs() {
  const { user, refresh } = useAuth();
  const location = useLocation();
  const navigate = useNavigate();
  const [profiles, setProfiles] = useState([]);
  const [activeProfile, setActiveProfile] = useState(null);
  const [view, setView] = useState('profiles'); // profiles | profile_home | chat | catalog | vault
  const [loadingProfiles, setLoadingProfiles] = useState(true);
  const [showTopup, setShowTopup] = useState(false);
  const [disclaimerAccepted, setDisclaimerAccepted] = useState(
    () => localStorage.getItem('legal_disclaimer_accepted') === '1'
  );

  const token = localStorage.getItem('jhp_token');
  const headers = { Authorization: `Bearer ${token}` };

  useEffect(() => {
    const load = async () => {
      try {
        const res = await axios.get(`${API}/api/legal/profiles`, { headers });
        setProfiles(res.data);
      } catch {
        // silent — user may be on free plan
      } finally {
        setLoadingProfiles(false);
      }
    };
    load();
  }, []);

  // Handle Stripe topup return URL: /legal?topup=success&credits=35
  useEffect(() => {
    const params = new URLSearchParams(location.search);
    if (params.get('topup') === 'success') {
      const credits = params.get('credits');
      toast.success(`${credits} legal credits added to your account!`);
      refresh?.(); // refresh user object so credit balance updates
      navigate('/legal', { replace: true }); // strip query params
    }
  }, [location.search]);

  const acceptDisclaimer = () => {
    localStorage.setItem('legal_disclaimer_accepted', '1');
    setDisclaimerAccepted(true);
  };

  const selectProfile = (profile) => {
    setActiveProfile(profile);
    setView('profile_home');
  };

  const refreshProfile = async () => {
    if (!activeProfile) return;
    try {
      const res = await axios.get(`${API}/api/legal/profiles`, { headers });
      setProfiles(res.data);
      const updated = res.data.find(p => p.id === activeProfile.id);
      if (updated) setActiveProfile(updated);
    } catch {}
  };

  const handleIntakeComplete = async () => {
    await refreshProfile();
    setView('catalog');
  };

  const handleGenerated = async () => {
    await refreshProfile();
    setView('vault');
  };

  // ── Disclaimer gate ──────────────────────────────────────────────────────
  if (!disclaimerAccepted) {
    return (
      <div className="max-w-2xl mx-auto px-4 py-16">
        <div className="rounded-2xl border border-amber-500/30 bg-amber-500/5 p-8">
          <div className="flex items-center gap-3 mb-5">
            <div className="w-10 h-10 rounded-xl bg-amber-500/10 border border-amber-500/20 flex items-center justify-center">
              <Scale className="w-5 h-5 text-amber-400" />
            </div>
            <h2 className="text-xl font-heading font-bold text-white">Legal Documents — Important Notice</h2>
          </div>
          <p className="text-zinc-300 text-sm leading-relaxed mb-6">{DISCLAIMER_TEXT}</p>
          <div className="rounded-lg bg-zinc-900/60 border border-zinc-700 p-4 mb-6 text-xs text-zinc-400 leading-relaxed">
            By using this feature you acknowledge that generated documents are drafts only,
            require professional legal review, and NovaJay Tech bears no liability for
            their use. Laws vary by jurisdiction and change over time. Generation date
            and jurisdiction are stamped on every document.
          </div>
          <button
            onClick={acceptDisclaimer}
            className="w-full py-3 bg-indigo-600 hover:bg-indigo-500 text-white font-medium rounded-xl transition-colors"
          >
            I understand — continue to Legal Documents
          </button>
        </div>
      </div>
    );
  }

  // ── Page layout ──────────────────────────────────────────────────────────
  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      {/* Top bar */}
      <div className="flex items-center justify-between mb-8 flex-wrap gap-4">
        <div className="flex items-center gap-3">
          {view !== 'profiles' && (
            <button
              onClick={() => {
                if (view === 'profile_home') setView('profiles');
                else setView('profile_home');
              }}
              className="p-2 text-zinc-400 hover:text-white hover:bg-zinc-800 rounded-lg transition-colors"
            >
              <ArrowLeft className="w-5 h-5" />
            </button>
          )}
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-indigo-500 to-violet-500 flex items-center justify-center">
            <Scale className="w-5 h-5 text-white" />
          </div>
          <div>
            <h1 className="text-xl font-heading font-bold text-gradient">Legal Documents</h1>
            <p className="text-xs text-zinc-500">
              AI-drafted · Requires lawyer review · 2026 law context
            </p>
          </div>
        </div>

        {/* Credit display + topup */}
        {user?.legal && (
          <div className="flex items-center gap-2">
            <div className="flex items-center gap-2 px-3 py-2 bg-zinc-800/60 rounded-xl border border-zinc-700">
              <Zap className="w-4 h-4 text-indigo-400" />
              <span className="text-sm text-zinc-300">
                <span className="font-semibold text-white">{user.legal.total_available}</span>
                <span className="text-zinc-500"> credits</span>
              </span>
              {user.tier === 'free' && (
                <Lock className="w-3.5 h-3.5 text-zinc-600 ml-1" />
              )}
            </div>
            {user.tier !== 'free' && (
              <button
                onClick={() => setShowTopup(true)}
                title="Buy more credits"
                className="flex items-center gap-1.5 px-3 py-2 text-xs font-medium text-indigo-400 bg-indigo-500/10 hover:bg-indigo-500/20 border border-indigo-500/20 hover:border-indigo-500/40 rounded-xl transition-all"
              >
                <Plus className="w-3.5 h-3.5" /> Buy credits
              </button>
            )}
          </div>
        )}
      </div>

      {/* Breadcrumb */}
      {view !== 'profiles' && (
        <div className="flex items-center gap-2 text-xs text-zinc-500 mb-6 flex-wrap">
          <button onClick={() => setView('profiles')} className="hover:text-zinc-300 transition-colors">
            Profiles
          </button>
          <ChevronRight className="w-3 h-3" />
          <button onClick={() => setView('profile_home')} className="hover:text-zinc-300 transition-colors">
            {activeProfile?.name}
          </button>
          {view !== 'profile_home' && (
            <>
              <ChevronRight className="w-3 h-3" />
              <span className="text-zinc-400 capitalize">{view === 'catalog' ? 'Select Documents' : view === 'chat' ? 'Intake Chat' : 'Document Vault'}</span>
            </>
          )}
        </div>
      )}

      {/* ── Profiles list ── */}
      {view === 'profiles' && (
        <ProfileManager
          profiles={profiles}
          user={user}
          onSelect={selectProfile}
          onCreated={(p) => { setProfiles(prev => [p, ...prev]); selectProfile(p); }}
          onDeleted={(id) => setProfiles(prev => prev.filter(p => p.id !== id))}
        />
      )}

      {/* ── Profile home — 3 action cards ── */}
      {view === 'profile_home' && activeProfile && (
        <div className="max-w-2xl mx-auto">
          <div className="mb-6">
            <div className="flex items-center gap-2 mb-1">
              <Building2 className="w-4 h-4 text-zinc-400" />
              <h2 className="text-lg font-heading font-bold text-white">{activeProfile.name}</h2>
            </div>
            <p className="text-sm text-zinc-500">
              {activeProfile.intake_complete
                ? 'Intake complete — ready to generate documents.'
                : 'Start the intake chat to tell the AI about your business.'}
            </p>
          </div>

          <div className="grid gap-4">
            {/* Chat intake */}
            <button
              onClick={() => setView('chat')}
              className="group rounded-2xl border border-zinc-800 bg-zinc-900/60 p-6 text-left hover:border-indigo-500/40 hover:bg-indigo-500/5 transition-all"
            >
              <div className="flex items-start justify-between">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-xl bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center">
                    <MessageSquare className="w-5 h-5 text-indigo-400" />
                  </div>
                  <div>
                    <div className="flex items-center gap-2">
                      <p className="font-medium text-white">Business Intake Chat</p>
                      {activeProfile.intake_complete && (
                        <span className="text-xs text-emerald-400 bg-emerald-400/10 border border-emerald-400/20 px-2 py-0.5 rounded-full">Done</span>
                      )}
                    </div>
                    <p className="text-sm text-zinc-500 mt-0.5">
                      {activeProfile.intake_complete
                        ? 'View or continue the intake conversation'
                        : 'Answer a few questions so we can tailor your documents'}
                    </p>
                  </div>
                </div>
                <ChevronRight className="w-5 h-5 text-zinc-600 group-hover:text-indigo-400 transition-colors mt-1" />
              </div>
            </button>

            {/* Document catalog */}
            <button
              onClick={() => setView('catalog')}
              className="group rounded-2xl border border-zinc-800 bg-zinc-900/60 p-6 text-left hover:border-indigo-500/40 hover:bg-indigo-500/5 transition-all"
            >
              <div className="flex items-start justify-between">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-xl bg-violet-500/10 border border-violet-500/20 flex items-center justify-center">
                    <FileText className="w-5 h-5 text-violet-400" />
                  </div>
                  <div>
                    <p className="font-medium text-white">Document Catalog</p>
                    <p className="text-sm text-zinc-500 mt-0.5">
                      Select and generate legal, finance, HR, and corporate documents
                    </p>
                  </div>
                </div>
                <ChevronRight className="w-5 h-5 text-zinc-600 group-hover:text-violet-400 transition-colors mt-1" />
              </div>
            </button>

            {/* Document vault */}
            <button
              onClick={() => setView('vault')}
              className="group rounded-2xl border border-zinc-800 bg-zinc-900/60 p-6 text-left hover:border-indigo-500/40 hover:bg-indigo-500/5 transition-all"
            >
              <div className="flex items-start justify-between">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-xl bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center">
                    <FolderOpen className="w-5 h-5 text-emerald-400" />
                  </div>
                  <div>
                    <p className="font-medium text-white">Document Vault</p>
                    <p className="text-sm text-zinc-500 mt-0.5">
                      View, copy, download, and regenerate your generated documents
                    </p>
                  </div>
                </div>
                <ChevronRight className="w-5 h-5 text-zinc-600 group-hover:text-emerald-400 transition-colors mt-1" />
              </div>
            </button>
          </div>
        </div>
      )}

      {/* ── Chat intake ── */}
      {view === 'chat' && activeProfile && (
        <div className="max-w-3xl mx-auto h-[680px] flex flex-col">
          <ChatIntake
            profile={activeProfile}
            onIntakeComplete={handleIntakeComplete}
          />
        </div>
      )}

      {/* ── Document catalog ── */}
      {view === 'catalog' && activeProfile && (
        <DocumentCatalog
          profile={activeProfile}
          user={user}
          onGenerate={handleGenerated}
          onBuyCredits={() => setShowTopup(true)}
        />
      )}

      {/* ── Document vault ── */}
      {view === 'vault' && activeProfile && (
        <DocumentVault profile={activeProfile} />
      )}

      {/* Topup modal */}
      {showTopup && <TopupModal onClose={() => setShowTopup(false)} />}
    </div>
  );
}
